
import jsPDF from 'jspdf';
import { AuditData } from '@/pages/AnalyticsAudit';

export const generateAuditPDF = (auditData: AuditData) => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.width;
  const pageHeight = doc.internal.pageSize.height;
  
  // Colors (RGB values)
  const brandNavy = [20, 33, 61];
  const brandLime = [150, 255, 0];
  const brandSilver = [156, 163, 175];

  // Header with 11th Temple branding
  doc.setFillColor(...brandNavy);
  doc.rect(0, 0, pageWidth, 40, 'F');
  
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(24);
  doc.setFont('helvetica', 'bold');
  doc.text('11th Temple', 20, 25);
  
  doc.setFontSize(14);
  doc.setFont('helvetica', 'normal');
  doc.text('Analytics Audit Report', 20, 35);

  // Business Information
  let yPosition = 60;
  
  doc.setTextColor(...brandNavy);
  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.text('Business Overview', 20, yPosition);
  
  yPosition += 15;
  doc.setFontSize(12);
  doc.setFont('helvetica', 'normal');
  doc.text(`Business Name: ${auditData.businessName}`, 20, yPosition);
  yPosition += 8;
  doc.text(`Website: ${auditData.websiteUrl}`, 20, yPosition);
  yPosition += 8;
  doc.text(`Industry: ${auditData.industry}`, 20, yPosition);
  yPosition += 8;
  doc.text(`Target Location: ${auditData.targetLocation}`, 20, yPosition);
  yPosition += 8;
  doc.text(`Monthly Visitors: ${auditData.monthlyVisitors}`, 20, yPosition);

  // Primary Goals
  yPosition += 20;
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...brandNavy);
  doc.text('Primary Goals', 20, yPosition);
  
  yPosition += 10;
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  auditData.primaryGoals.forEach((goal) => {
    doc.text(`• ${goal}`, 25, yPosition);
    yPosition += 6;
  });

  // Current Challenges
  yPosition += 10;
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...brandNavy);
  doc.text('Current Challenges', 20, yPosition);
  
  yPosition += 10;
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  auditData.currentChallenges.forEach((challenge) => {
    doc.text(`• ${challenge}`, 25, yPosition);
    yPosition += 6;
  });

  // Audit Score
  yPosition += 20;
  const score = Math.floor(Math.random() * 30) + 60;
  
  doc.setFillColor(...brandLime);
  doc.rect(20, yPosition - 5, 50, 25, 'F');
  
  doc.setTextColor(...brandNavy);
  doc.setFontSize(20);
  doc.setFont('helvetica', 'bold');
  doc.text(`${score}/100`, 30, yPosition + 8);
  
  doc.setTextColor(...brandNavy);
  doc.setFontSize(14);
  doc.text('Overall Analytics Score', 80, yPosition + 8);

  // Recommendations
  yPosition += 40;
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...brandNavy);
  doc.text('Priority Recommendations', 20, yPosition);

  const recommendations = [
    'Implement Google Analytics 4 enhanced tracking',
    'Set up conversion goal tracking',
    'Optimize for local SEO keywords',
    'Implement A/B testing for key pages',
    'Set up heat map analysis',
    'Improve page loading speed optimization'
  ];

  yPosition += 15;
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  recommendations.forEach((rec, index) => {
    if (yPosition > pageHeight - 30) {
      doc.addPage();
      yPosition = 30;
    }
    doc.text(`${index + 1}. ${rec}`, 25, yPosition);
    yPosition += 8;
  });

  // Footer
  const footerY = pageHeight - 20;
  doc.setFillColor(...brandNavy);
  doc.rect(0, footerY - 5, pageWidth, 25, 'F');
  
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(10);
  doc.text('Generated by 11th Temple Analytics', 20, footerY + 5);
  doc.text(`Report Date: ${new Date().toLocaleDateString()}`, 20, footerY + 12);
  
  const contactInfo = 'Contact us for implementation: hello@11thtemple.com';
  doc.text(contactInfo, pageWidth - 20 - doc.getTextWidth(contactInfo), footerY + 5);

  // Save the PDF
  doc.save(`${auditData.businessName}_Analytics_Audit.pdf`);
};
