import jsPDF from "jspdf";

// ServiceData type is minimal and internal here.
type ServiceData = {
  title: string;
  description: string;
  bullets: string[];
};

function addLogo(doc: jsPDF, x: number, y: number, width: number, cb: () => void) {
  const logoUrl = "/lovable-uploads/87c7e72a-88ad-4a5e-bd58-1bff5a3dee6b.png";
  const img = new Image();
  img.crossOrigin = "anonymous";
  img.onload = function () {
    try {
      const canvas = document.createElement("canvas");
      canvas.width = img.width;
      canvas.height = img.height;
      const ctx = canvas.getContext("2d");
      ctx?.drawImage(img, 0, 0);
      const imgData = canvas.toDataURL("image/png");
      doc.addImage(imgData, "PNG", x, y, width, (img.height / img.width) * width);
    } finally {
      cb();
    }
  };
  img.onerror = cb;
  img.src = logoUrl;
}

// Brand palette
const navy = [20, 33, 61] as const;
const lime = [150, 255, 0] as const;
const silver = [156, 163, 175] as const;

export async function generateServicesPDF(services: ServiceData[]) {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.width;
  const pageHeight = doc.internal.pageSize.height;

  // Header (Brand color and logo)
  doc.setFillColor(...navy);
  doc.rect(0, 0, pageWidth, 36, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(22);
  doc.text("11th Temple Solutions", 20, 22);

  doc.setFontSize(14);
  doc.setFont("helvetica", "normal");
  doc.text("AI Service Guide", 20, 32);

  // Add logo async
  await new Promise<void>(resolve => {
    addLogo(doc, pageWidth - 36, 7, 26, resolve);
  });

  // Section: Introduction
  let y = 48;
  doc.setFontSize(17);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(...navy);
  doc.text("Unlock Your Business Potential with AI Automation", 20, y);
  y += 12;
  doc.setFontSize(11);
  doc.setTextColor(...silver);
  doc.text(
    "Comprehensive solutions for local businesses, blending cutting-edge tech with market knowledge.",
    20, y, { maxWidth: pageWidth - 38 }
  );

  // Page 2: Services
  doc.addPage();
  doc.setFillColor(...navy);
  doc.rect(0, 0, pageWidth, 36, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(22);
  doc.text("AI Service Overview", 20, 22);

  // Add logo on page 2
  await new Promise<void>(resolve => {
    addLogo(doc, pageWidth - 36, 7, 26, resolve);
  });

  y = 44;
  const serviceBlockHeight = 35;
  services.forEach((service, idx) => {
    if (y > pageHeight - 45) {
      doc.addPage();
      y = 44;
    }
    doc.setFontSize(15);
    doc.setTextColor(...lime);
    doc.setFont("helvetica", "bold");
    doc.text(service.title, 20, y);
    y += 8;
    doc.setFont("helvetica", "normal");
    doc.setFontSize(11);
    doc.setTextColor(...navy);
    doc.text(service.description, 20, y, { maxWidth: pageWidth - 38 });
    y += 8.5;
    service.bullets.forEach((b, j) => {
      doc.setTextColor(...silver);
      doc.setFontSize(10);
      doc.text(`• ${b}`, 25, y);
      y += 5.5;
    });
    y += 6;
  });

  // Final page: CTA
  doc.addPage();
  doc.setFillColor(...navy);
  doc.rect(0, 0, pageWidth, 36, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(20);
  doc.text("Ready to Start Your AI Journey?", 20, 22);

  await new Promise<void>(resolve => {
    addLogo(doc, pageWidth - 36, 7, 26, resolve);
  });

  y = 56;
  doc.setFont("helvetica", "normal");
  doc.setTextColor(...silver);
  doc.setFontSize(13);
  doc.text(
    "Contact us today for a free consultation and discover how our AI automation solutions can transform your local business.\nhello@11thtemplesolutions.com | +44 7312 190 728",
    20, y, { maxWidth: pageWidth - 38 }
  );

  // Footer brand & date for each page
  for (let i = 1; i <= doc.getNumberOfPages(); i++) {
    doc.setPage(i);
    const footerY = pageHeight - 18;
    doc.setFillColor(...navy);
    doc.rect(0, footerY - 5, pageWidth, 22, 'F');
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(10);
    doc.text('Generated by 11th Temple Solutions', 18, footerY + 5);
    const dateStr = new Date().toLocaleDateString();
    doc.text(`Service Guide Date: ${dateStr}`, pageWidth - 64, footerY + 5);
  }
  doc.save("11th_Temple_AI_Services.pdf");
}
