// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://itlzwuvxepyawzzxrxia.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml0bHp3dXZ4ZXB5YXd6enhyeGlhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwMTgzMzcsImV4cCI6MjA2NTU5NDMzN30.jbFsx1YNjKp9CvRSSvjZzihSgVRUIga2BcGws8peq78";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);